[macOS] add -dumplog switch to installer command (#36)
I've gotten some reports of pkg files failing to install on macOS
Catalina, something like:

    Querying https://software.xamarin.com/Service/Updates?v=2&pv964ebddd-1ffe-47e7-8128-5ce17ffffb05=0&pv4569c276-1397-4adb-9485-82a7696df22e=0&pvd1ec039f-f3db-468b-a508-896d7c382999=0&pv0ab364ff-c0e9-43a8-8747-3afb02dc7731=0&level=Stable
    Downloading https://download.visualstudio.microsoft.com/download/pr/8f94ca38-039a-4c9f-a51a-a6cb33c76a8c/aa46188c5f7a2e0c6f2d4bd4dc261604/xamarin.android-10.2.0.100.pkg
    Writing to /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/7kjmmg6c.nw4.pkg
    Deleting /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/7kjmmg6c.nw4.pkg
    An error occurred when executing task 'provision-androidsdk'.
    Error: One or more errors occurred. ('/usr/bin/sudo' with arguments '/usr/sbin/installer -pkg "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/7kjmmg6c.nw4.pkg" -target / -verbose' exited with code 137)
        '/usr/bin/sudo' with arguments '/usr/sbin/installer -pkg "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/7kjmmg6c.nw4.pkg" -target / -verbose' exited with code 137

Searching the web, code 137 seems like it means "out of memory".

We definitely don't have any log output, so hoping `-dumplog` will help.

I also made some files not visible in IDEs.